import { Inter } from 'next/font/google'
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import CustomNavbar from '@/components/CustomNavbar'
import Footer from '@/components/Footer';
import { ToastContainer } from 'react-toastify';
import { connectDB } from "@/helper/db";
import UserProvider from './context/userProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Work Manager App',
  description: 'Generated by create next app'
};
// connectDB();

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ToastContainer />
          <CustomNavbar />
          <div className='py-20 dark:bg-slate-950 bg-slate-50 w-full h-full'>{children}</div>
          <Footer />
        </UserProvider>
      </body>

    </html>
  )
}
